<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$formKey       = $objectManager->get('Magento\Framework\Data\Form\FormKey');
?>

<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php if ($_product->isSaleable()): ?>
<div class="box-tocart">
    <div class="fieldset">
        <?php if ($block->shouldRenderQuantity()): ?>
        <div class="field qty">
            <div class="control" data-bind="scope: 'qty_change'">
                <input type="hidden" name="form_key" value="<?php echo $formKey->getFormKey() ?>" />
                <button class="btn btn-minus"  data-bind="click: decreaseQty"></button>
                <input type="number"
                       name="qty"
                       id="qty"
                       value="<?=  $block->getProductDefaultQty() * 1 ?>"
                       title="<?=  __('Qty') ?>"
                       class="input-text qty"
                       data-validate="<?= $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                />
                <button class="btn btn-plus" data-bind="click: increaseQty"></button>
            </div>
        </div>
        <?php endif; ?>
        <div class="actions">
            <button type="submit"
                    title="<?=  $buttonTitle ?>"
                    class="action primary tocart"
                    id="product-addtocart-button">
                <span><?=  $buttonTitle ?></span>
            </button>
            <?= $block->getChildHtml('', true) ?>
        </div>
    </div>
</div>
<?php endif; ?>

<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/js/validate-product": {}
        }
    }
</script>