<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php $_product = $block->getProduct() ?>
<a href="<?= /* @escapeNotVerified */ $this->helper('Magento\Catalog\Helper\Product')->getEmailToFriendUrl($_product) ?>"
       class="action twitter"><span><?= /* @escapeNotVerified */ __('Twitter') ?></span></a>
<a href="<?= /* @escapeNotVerified */ $this->helper('Magento\Catalog\Helper\Product')->getEmailToFriendUrl($_product) ?>"
   class="action facebook"><span><?= /* @escapeNotVerified */ __('Facebook') ?></span></a>
<a href="<?= /* @escapeNotVerified */ $this->helper('Magento\Catalog\Helper\Product')->getEmailToFriendUrl($_product) ?>"
   class="action pin"><span><?= /* @escapeNotVerified */ __('Pintrest') ?></span></a>


