<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * Product description template
 *
 * @var $block \Magento\Catalog\Block\Product\View\Description
 */
//var_dump($block->getProduct()->getCategoryIds());die;
?>
<div class="page-title-wrapper product">
	<span class="type-name"><?php // echo $block->getProduct()->getCategory() ?></span>
	<h1 class="page-title">
	<span class="base" data-ui-id="page-title-wrapper" itemprop="name">
		<?php echo $block->getProduct()->getName() ?>
	</span>
	</h1>
</div>
<?php //echo  $this->helper('Magento\Catalog\Helper\Output')->productAttribute($block->getProduct(), $block->getProduct()->getDescription(), 'description') ?>
