<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
?>

<?php /** @var \Magento\Framework\Pricing\Render\Amount $block */ ?>

<span class="price-container <?=  $block->getAdjustmentCssClasses() ?>"
        <?= $block->getSchema() ? ' itemprop="offers" itemscope itemtype="http://schema.org/Offer"' : '' ?>>
    <div class="">
    <?php if ($block->getDisplayLabel()): ?>
        <span class="price-label">Was : </span>
    <?php endif; ?>
            <span <?php if ($block->getPriceId()): ?> id="<?=  $block->getPriceId() ?>"<?php endif;?>
                <?= ($block->getPriceDisplayLabel()) ? 'data-label="' . $block->getPriceDisplayLabel() . $block->getPriceDisplayInclExclTaxes() . '"' : '' ?>
                    data-price-amount="<?=  $block->getDisplayValue() ?>"
                    data-price-type="<?=  $block->getPriceType() ?>"
                    class="price-wrapper <?=  $block->getPriceWrapperCss() ?>">
        <?=  $block->formatCurrency($block->getDisplayValue(), (bool)$block->getIncludeContainer()) ?>
    </span>
</div>
    <?php if ($block->hasAdjustmentsHtml()): ?>
        <?= $block->getAdjustmentsHtml() ?>
    <?php endif; ?>
    <?php if ($block->getSchema()): ?>
        <meta itemprop="price" content="<?=  $block->getDisplayValue() ?>" />
        <meta itemprop="priceCurrency" content="<?=  $block->getDisplayCurrencyCode() ?>" />
    <?php endif; ?>
</span>
