<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
$toolbarBlock = $block->getLayout()->createBlock('\Magento\Catalog\Block\Product\ProductList\Toolbar');
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty"><div><?=  __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>
    <?= $block->getToolbarHtml() ?>
    <?= $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $image = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $image = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>

    <div class="block widget block-products-list grid grid-4" >
        <div class="products wrapper <?=  $viewMode ?> products-<?=  $viewMode ?>">
        <?php $iterator = 1; ?>
        <ol class="products list items product-items">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product): ?>
                <?=  ($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
                <div class="product-item-info" data-container="product-grid">
                    <?php
                    $productImage = $block->getImage($_product, $image);
                    if ($pos != null) {
                        $position = ' style="left:' . $productImage->getWidth() . 'px;'
                            . 'top:' . $productImage->getHeight() . 'px;"';
                    }
                    ?>
                    <div class="product-item-name">
                        <?=  $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                    </div>
                    <?php // Product Image ?>
                    <a href="<?=  $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                        <?= $productImage->toHtml() ?>
                    </a>
                    <div class="product details product-item-details">
                        <?php
                            $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                        ?>
                        <?= $block->getReviewsSummaryHtml($_product, $templateType) ?>
                        <?=  $block->getProductPrice($_product) ?>
                        <?= $block->getProductDetailsHtml($_product) ?>

                        <div class="product-item-inner">
                            <div class="product actions product-item-actions"<?= strpos($pos, $viewMode . '-actions') ? $position : '' ?>>
                                <div class="actions-primary"<?= strpos($pos, $viewMode . '-primary') ? $position : '' ?>>
                                    <?php if ($_product->isSaleable()): ?>
                                        <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                        <form data-role="tocart-form" data-product-sku="<?= $block->escapeHtml($_product->getSku()) ?>" action="<?=  $postParams['action'] ?>" method="post">
                                            <input type="hidden" name="product" value="<?=  $postParams['data']['product'] ?>">
                                            <input type="hidden" name="<?=  Action::PARAM_NAME_URL_ENCODED ?>" value="<?=  $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                            <?= $block->getBlockHtml('formkey') ?>
                                            <button type="submit"
                                                    title="<?= $block->escapeHtml(__('Quickshop')) ?>"
                                                    class="action tocart primary">
                                                <span><?=  __('Quickshop') ?></span>
                                            </button>
                                        </form>
                                    <?php else: ?>
                                        <?php if ($_product->isAvailable()): ?>
                                            <div class="stock available"><span><?=  __('In stock') ?></span></div>
                                        <?php else: ?>
                                            <div class="stock unavailable"><span><?=  __('Out of stock') ?></span></div>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                </div>
                                <!--<div data-role="add-to-links" class="actions-secondary"<?/*= strpos($pos, $viewMode . '-secondary') ? $position : '' */?>>
                                    <?php /*if ($addToBlock = $block->getChildBlock('addto')): */?>
                                        <?/*= $addToBlock->setProduct($_product)->getChildHtml() */?>
                                    <?php /*endif; */?>
                                </div>-->
                            </div>
                            <?php /*if ($showDescription):*/?><!--
                                <div class="product description product-item-description">
                                    <?/*=  $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') */?>
                                    <a href="<?/*=  $_product->getProductUrl() */?>" title="<?/*=  $_productNameStripped */?>"
                                       class="action more"><?/*=  __('Learn More') */?></a>
                                </div>
                            --><?php /*endif;*/ ?>
                        </div>
                    </div>
                </div>
                <?= ($iterator == count($_productCollection)+1) ? '</li>' : '' ?>
            <?php endforeach; ?>
        </ol>
    </div>
    </div>
    <?= $block->getToolbarHtml() ?>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {
                    "product_sku": "<?=  $_product->getSku() ?>"
                }
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>
<style>
    .page-main .block-products-list {
        max-width: 75em;
        margin: 0 auto;
    }
    .page-layout-1column .toolbar-products {
        position: relative;
    }
    .toolbar-products .pages {
        display: block;
        margin-bottom: 0;
    }
    .page-layout-1column.page-with-filter .column.main {
        padding-top: 0 !important;
    }
</style>