<?php
use Magento\Framework\App\Action\Action;

$objectManager =  \Magento\Framework\App\ObjectManager::getInstance();
$abstractProductBlock = $block->getLayout()->createBlock('\Magento\Catalog\Block\Product\AbstractProduct');
$productCollectionFactory = $objectManager->get('\Magento\Catalog\Model\ResourceModel\Product\CollectionFactory');
$collection = $productCollectionFactory->create();
//$productCollection = $objectManager->create('\Magento\Reports\Model\ResourceModel\Report\Collection\Factory');
//$collection = $productCollection->create('\Magento\Sales\Model\ResourceModel\Report\Bestsellers\Collection');
//$collection->setPeriod('month');
$collection->addAttributeToSelect('*');
$collection->setPageSize(6); // selecting only 3 products
$store = $objectManager->get('Magento\Store\Model\StoreManagerInterface')->getStore();

$productBlock = $block->getLayout()->createBlock('\Magento\Catalog\Block\Product\ListProduct');

?>


<div>
    <div class="content-heading">
        <p class="info">Buyers guide</p>
        <h2 class="title">Best Sellers</h2>
    </div>
    <div class="block widget block-products-list grid">
        <div class="block-content">
            <div class="products-grid grid swiper-container">
                <ol class="product-items widget-product-grid swiper-wrapper">
                	<?php foreach ($collection as $product) { 
                		$productImageUrl = $store->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA) . 'catalog/product' . $product->getData('image');
                		$postParams = $productBlock->getAddToCartPostParams($product);                 		
            		?>
	                    <li class="product-item swiper-slide">
	                        <div class="product-item-info">
	                            <div class="product-item-name">
	                                <?php echo $product->getName(); ?>
	                            </div>
	                            <a href="<?php echo $product->getProductUrl(); ?>" class="product-item-photo">
	                                <span class="product-image-container">
	                                <span class="product-image-wrapper">
	                                  <img src="<?php echo $productImageUrl; ?>" class="product-image-photo">
	                                </span>
	                                </span>
	                            </a>
	                            <div class="product-item-details">
	                                <div class="price-box price-final_price">
	                                    <span class="price-container price-final_price tax weee">
	                                  		<span class="price-wrapper">
	                                    		<span class=""><?php echo $abstractProductBlock->getProductPrice($product); ?></span>
                                    		</span>
                                    	</span>
	                                </div>
	                            	<div class="product-item-actions">
	                                    <div class="actions-primary">
	                                    	<?php if($product->isSaleable()) { ?>
		                                        <form data-role="tocart-form" action="<?php  echo $postParams['action']; ?>" method="post">
                                                    <input type="hidden" name="product" value="<?php  echo $postParams['data']['product']; ?>">
                                                    <input type="hidden" name="<?=  Action::PARAM_NAME_URL_ENCODED ?>" value="<?=  $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                                    <?php echo $block->getBlockHtml('formkey')?>
                                                    <button type="submit"
                                                            title="<?php echo $block->escapeHtml(__('Quickshop')); ?>"
                                                            class="action tocart primary btn btn-filled btn-sm btn-submit btn-block">
                                                        <span><?php  echo __('Quickshop') ?></span>
                                                    </button>
                                                </form>
		                                    <?php } ?>
		                                </div>
	                                </div>
	                            </div>
	                        </div>
	                    </li>                		
                	<?php } ?>
                </ol>
                <div class="swiper-pagination"></div>
                <div class="swiper-button-next">
                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 27 44"><path d="M27,22L27,22L5,44l-2.1-2.1L22.8,22L2.9,2.1L5,0L27,22L27,22z"></svg>
                </div>
                <div class="swiper-button-prev">
                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 27 44"><path d="M0,22L22,0l2.1,2.1L4.2,22l19.9,19.9L22,44L0,22L0,22L0,22z"></svg>
                </div>
            </div>
        </div>
    </div>
</div>

