<div class="bg-white news-section">
    <div class="blocks-promo">
        <div class="block-promo-wrapper block-promo-hp">
            <a href="#" class="block-promo">
                <img src="<?php echo $this->getViewFileUrl('images/news/news2.png'); ?>" />
                <span class="content">
                    <strong class="title">New arrival: Haute Cabriere Chardonnay Pinot Noir 2017</strong>
                    <span class="date">08 / 05 / 18</span>
                </span>
            </a>
            <a href="#" class="block-promo">
                <img src="<?php echo $this->getViewFileUrl('images/news/news3.png'); ?>" />
                <span class="content">
                    <strong class="title">Alvarinho - a truly celebrated wine!</strong>
                    <span class="date">08 / 05 / 18</span>
                </span>
            </a>
            <a href="#" class="block-promo">
                <img src="<?php echo $this->getViewFileUrl('images/news/news1.png'); ?>" />
                <span class="content">
                    <strong class="title">La couronne: the crown of franschhoek part 2</strong>
                    <span class="date">08 / 05 / 18</span>
                </span>
            </a>
        </div>
        <div class="block-promo-wrapper block-promo-hp">
            <a href="#" class="block-promo">
                <img src="<?php echo $this->getViewFileUrl('images/news/news2.png'); ?>" />
                <span class="content">
                    <strong class="title">New arrival: Haute Cabriere Chardonnay Pinot Noir 2017</strong>
                    <span class="date">08 / 05 / 18</span>
                </span>
            </a>
            <a href="#" class="block-promo">
                <img src="<?php echo $this->getViewFileUrl('images/news/news3.png'); ?>" />
                <span class="content">
                    <strong class="title">Alvarinho - a truly celebrated wine!</strong>
                    <span class="date">08 / 05 / 18</span>
                </span>
            </a>
            <a href="#" class="block-promo">
                <img src="<?php echo $this->getViewFileUrl('images/news/news1.png'); ?>" />
                <span class="content">
                    <strong class="title">La couronne: the crown of franschhoek part 2</strong>
                    <span class="date">08 / 05 / 18</span>
                </span>
            </a>
        </div>
        <div class="block-promo-wrapper block-promo-hp">
            <a href="#" class="block-promo">
                <img src="<?php echo $this->getViewFileUrl('images/news/news2.png'); ?>" />
                <span class="content">
                    <strong class="title">New arrival: Haute Cabriere Chardonnay Pinot Noir 2017</strong>
                    <span class="date">08 / 05 / 18</span>
                </span>
            </a>
            <a href="#" class="block-promo">
                <img src="<?php echo $this->getViewFileUrl('images/news/news3.png'); ?>" />
                <span class="content">
                    <strong class="title">Alvarinho - a truly celebrated wine!</strong>
                    <span class="date">08 / 05 / 18</span>
                </span>
            </a>
            <a href="#" class="block-promo">
                <img src="<?php echo $this->getViewFileUrl('images/news/news1.png'); ?>" />
                <span class="content">
                    <strong class="title">La couronne: the crown of franschhoek part 2</strong>
                    <span class="date">08 / 05 / 18</span>
                </span>
            </a>
        </div>
    </div>
</div>