<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<div class="connect-section">
    <div class="connect-container">
        <div>
            <span>Connect</span>
            <span class="social-section">
            <a href="https://twitter.com/hardtofindwines" class="social-icon">
            <i class="zmdi zmdi-twitter"></i>
            </a>
            <a href="https://www.facebook.com/Hard-to-Find-Wines-Ltd-232890465542/" class="social-icon">
            <i class="zmdi zmdi-facebook"></i>
            </a>
            <a href="https://plus.google.com/u/0/115877659943949941076/about" class="social-icon">
            <i class="zmdi zmdi-google-plus"></i>
            </a>
            </span>
        </div>
        <div>
            <span>Payment options</span>
            <span>
            <img src="<?php echo $this->getViewFileUrl('images/card/1.png'); ?>">
            <img src="<?php echo $this->getViewFileUrl('images/card/2.png'); ?>">
            <img src="<?php echo $this->getViewFileUrl('images/card/3.png'); ?>">
            <img src="<?php echo $this->getViewFileUrl('images/card/4.png'); ?>">
            </span>
        </div>
    </div>
</div>
<?php $block->getChildHtml('copyright')?>