<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<div class="copyright-section">
<small class="copyright">
    <span><?= /* @escapeNotVerified */ $block->getCopyright() ?></span>
    <span><?= 'Company Number: 06012515'?></span>
</small>
</div>
<script type="text/javascript">
    /*require(
     [
     'jquery'
     ],
     function(
     $
     ) {
     $(document).ready(function(){
     var $root = $('html, body');
     $('a[href^="#"]').click(function() {
     var href = $.attr(this, 'href');

     $root.animate({
     scrollTop: $(href).offset().top
     }, 1500, function () {
     window.location.hash = href;
     });

     return false;
     });
     });
     }
     );*/
</script>