<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

$headerBlock = $block->getLayout()->createBlock('\Magento\Theme\Block\Html\Topmenu');
$columnsLimit = 0; 
//$columnsLimit = $headerBlock->getColumnsLimit() ?: 0; 
$_menu = $headerBlock->getHtml('nav item', 'submenu', $columnsLimit);
?>
<button class="mobile-link-btn">QuickLinks</button>
<ul class="footer links" style="/* display: none; */">
    <li class="nav item">
        <a href="<?php echo $block->getUrl('about-us') ?>">About us</a>
    </li>
    <?php echo $_menu ?>
</ul>