<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var \Magento\Theme\Block\Html\Header $block
 */
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$baseUrl = $objectManager->get('Magento\Store\Model\StoreManagerInterface')->getStore()->getBaseUrl();

$headerBlock = $block->getLayout()->createBlock('\Magento\Theme\Block\Html\Topmenu');
$columnsLimit = $headerBlock->getColumnsLimit() ?: 0;
$_menu = $headerBlock->getHtml('level-top nav item', 'submenu', $columnsLimit);

$categoryFactory = $objectManager->create('Magento\Catalog\Model\ResourceModel\Category\CollectionFactory');
$categories = $objectManager->get('Magento\Catalog\Helper\Category')
                                   ->getStoreCategories();
?>


<div class="header-bar">
    <ul class="header links">
        <li class="nav item">
            <a href="<?php echo $block->getUrl('about-us') ?>">
                About us
            </a>
        </li>
        <?php
            $i = 0;
            foreach ($categories as $category){
                $categoryUrl = $baseUrl.$category->getData('request_path');

                if($i == ceil(($categories->count() - 1) /2)) {
                ?>
                </ul>
                <?= $block->getChildHtml() ?>
                <ul class="header links">
                    <li class="nav item">
                        <a href="<?php echo $categoryUrl; ?>"><?php echo $category->getName(); ?></a>
                    </li>
                <?php
                } else {
                    ?>
                    <li class="nav item">
                        <a href="<?php echo $categoryUrl; ?>"><?php echo $category->getName(); ?></a>
                    </li>
                    <?php
                }
                $i++;
            }
        ?>
    </ul>
</div>
