<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile


/**
 * Top menu for store
 *
 * @var $block \Magento\Theme\Block\Html\Topmenu
 */
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$customerSession = $objectManager->get('Magento\Customer\Model\Session');

?>
<?php $columnsLimit = $block->getColumnsLimit() ?: 0; ?>
<?php $_menu = $block->getHtml('level-top', 'submenu', $columnsLimit) ?>

<nav class="navigation" data-action="navigation">
    <ul class="ui-menu ui-widget ui-widget-content ui-corner-all">

	    <li class="level0 ui-menu-item">
	        <a href="#" class="level-top ui-corner-all">
	            <span>Offers</span>
	        </a>
	    </li>
	    <li class="level0 ui-menu-item">
	        <a href="#" class="level-top ui-corner-all">
	            <span>Rewards</span>
	        </a>
	    </li>
	    <li class="level0 ui-menu-item">
	        <a style="cursor: pointer;" class="level-top ui-corner-all">
	            <span>No minimum order</span>
	        </a>
	    </li>
	    <li class="level0 ui-menu-item">
	    	<?php // $block->getChildHtml()?>
	    	<?php echo $block->getChildHtml('topSearch') ?>
	    </li>
	    <li class="level0 ui-menu-item">
	        <a style="cursor: pointer;" class="level-top ui-corner-all">
	            <span>Free Delivery over £175</span>
	        </a>
	    </li>
	    <li class="level0 ui-menu-item">
	        <!-- <a href="#" class="level-top ui-corner-all">
	            <span>There is <span>1 item</span> in your Basket.</span>
	        </a> -->
	        <?php echo $block->getChildHtml('minicart') ?>
	    </li>
	    <!--<li class="level0 ui-menu-item">
            <?php /*if($customerSession->isLoggedIn()) { */?>
                <a href="<?php /*echo $block->getUrl('customer/account/logout') */?>" class="level-top ui-corner-all">
                    <span>Logout</span>
                </a>
            <?php /*} else { */?>
	        <a href="<?php /*echo $block->getUrl('customer/account/login') */?>" class="level-top ui-corner-all">
	            <span>Login</span>
	        </a>

            <?php /*} */?>
            <?php /*//echo $block->getChildHtml('my-account-link') */?>

	    </li>-->
        <?php if($customerSession->isLoggedIn()) { ?>
        <li class="level0 ui-menu-item customer-welcome">
            <span class="customer-name active" role="button" tabindex="0" data-toggle="dropdown" data-trigger-keypress-button="true" data-bind="scope: 'customer'" aria-haspopup="true" aria-expanded="true">
                <span data-bind="text: customer().fullname">Janki</span>
                <button type="button" class="action switch" tabindex="-1" data-action="customer-menu-toggle">
                <span>Change</span>
                </button>
            </span>
            <div class="customer-menu" data-target="dropdown" aria-hidden="false">
                <ul class="header links">
                    <li>
                        <a href="<?php echo $block->getUrl('customer/account/') ?>">My Account</a>
                    </li>
                    <li class="link wishlist" data-bind="scope: 'wishlist'">
                        <a href="<?php echo $block->getUrl('wishlist/') ?>">My Wish List</a>
                    </li>
                    <li class="authorization-link">
                        <a href="<?php echo $block->getUrl('customer/account/logout/')?>">
                            Sign Out
                        </a>
                    </li>
                </ul>
            </div>
        </li>
        <?php } else { ?>
        <li class="level0 ui-menu-item">
            <a href="<?php echo $block->getUrl('customer/account/login') ?>" class="level-top ui-corner-all">
                <span>Login</span>
            </a>
        </li>

        <?php } ?>
        <?php //echo $block->getChildHtml('my-account-link') ?>

    </ul>
</nav>