<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var \Magento\Theme\Block\Html\Header $block
 */
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$baseUrl = $objectManager->get('Magento\Store\Model\StoreManagerInterface')->getStore()->getBaseUrl();  

$headerBlock = $block->getLayout()->createBlock('\Magento\Theme\Block\Html\Topmenu');
$columnsLimit = $headerBlock->getColumnsLimit() ?: 0; 
$_menu = $headerBlock->getHtml('level-top nav item', 'submenu', $columnsLimit);

/*$categoryFactory = $objectManager->create('Magento\Catalog\Model\ResourceModel\Category\CollectionFactory');
$categories1 = $categoryFactory->create()                              
    ->addAttributeToSelect('*')
    ->setStore($storeManager->getStore())
    ->setPageSize(3)
    ->setCurPage(2);
*/

$categoryFactory = $objectManager->create('Magento\Catalog\Model\ResourceModel\Category\CollectionFactory');

/*$cat = $categoryFactory->addOrderField('id', 'DESC')->setPageSize(5);

echo "<pre>";print_r(get_class_methods($cat));die;*/

$categories = $objectManager->get('Magento\Catalog\Helper\Category')
                                   ->getStoreCategories();
                                   //->setOrder('id','DESC');




//echo "<pre>";print_r(get_class_methods($categories));die;
?>
<div class="header-bar">
    <ul class="header links">
        <li class="nav item">
            <a href="<?php echo $block->getUrl('customer/account/login') ?>">
                About us
            </a>
        </li>
        <?php //echo $_menu; ?>
        
        <?php 
            $i = 0;
            foreach ($categories as $category){
                

                $categoryUrl = $baseUrl.$category->getData('request_path');

                if($i == ceil(($categories->count() - 1) /2)) {
                ?>
                </ul>
                <a href="<?php echo $baseUrl; ?>" class="logo"><?= $block->getChildHtml() ?></a>
                <ul class="header links">
                    <li class="nav item">
                        <a href="<?php echo $categoryUrl; ?>"><?php echo $category->getName(); ?></a>
                    </li>
                <?php 
                } else {
                    ?>
                    <li class="nav item">
                        <a href="<?php echo $categoryUrl; ?>"><?php echo $category->getName(); ?></a>
                    </li>
                    <?php
                }
                $i++;
            }
        ?>
    </ul>
</div>
