<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var \Magento\Theme\Block\Html\Header $block
 */
$welcomeMessage = $block->getWelcome();

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeInformation = $objectManager->create('Magento\Store\Model\Information');
$store = $objectManager->create('Magento\Store\Model\Store');
$phone = $storeInformation->getStoreInformationObject($store)->getPhone();

$salesEmail = $objectManager->get('Magento\Framework\App\Config\ScopeConfigInterface')->getValue('trans_email/ident_general/email');
//$phone = $storeInfo->getPhone();

?>

    <ul class="header links">
        <li>
            <span>Connect</span>
            <span class="social-section">
                <a href="https://twitter.com/hardtofindwines" class="social-icon">
                <i class="zmdi zmdi-twitter"></i>
                </a>
                <a href="https://www.facebook.com/Hard-to-Find-Wines-Ltd-232890465542/" class="social-icon">
                <i class="zmdi zmdi-facebook"></i>
                </a>
                <a href="https://plus.google.com/u/0/115877659943949941076/about" class="social-icon">
                <i class="zmdi zmdi-google-plus"></i>
                </a>
            </span>
        </li>
        <li>
            <a href="#block-newsletter" class="btn btn-link btn-with-icon">
                <span>Subscribe to our newsletter</span>
            </a>
        </li>
    </ul>
    <ul class="header links">
        <li>
            <span>For Expert advice call:</span>
            <span>
      <a href="tel:<?php echo $phone; ?>"><?php echo $phone; ?></a>
    </span>
        </li>
        <li>
            <span>Email:</span>
            <span>
      <a href="mailto:<?php echo $salesEmail;?>"><?php echo $salesEmail;?></a>
    </span>
        </li>
    </ul>
    <ul class="header links visible-only-mobile">
        <li>
            <span>For Expert advice call:</span>
            <span>
      <a href="tel:<?php echo $phone; ?>"><?php echo $phone; ?></a>
    </span>
        </li>
        <li>
            <a href="#">
                <span class="flaticonsecure-047-password"></span>
            </a>
        </li>
        <li>
            <a href="#">
                <span class="flaticon-shopping-cart"></span>
            </a>
        </li>
    </ul>
<script type="text/javascript">
require(
        [
            'jquery'
        ],
        function(
            $
        ) {
            $(document).ready(function(){ 
                var $root = $('html, body');
                $('a[href^="#"]').click(function() {
                    var href = $.attr(this, 'href');

                    $root.animate({
                        scrollTop: $(href).offset().top
                    }, 1500, function () {
                        window.location.hash = href;
                    });

                    return false;
                });
            });
        }
    );
</script>