<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Form\Login\Info $block */
$backgroundImgUrl = $this->getViewFileUrl('images/login-banner.png');
?>
<?php if ($block->getRegistration()->isAllowed()): ?>
    <div class="line">
        <h4>OR</h4>
    </div>
    <div class="block block-new-customer" style="background-image: url('<?php echo $backgroundImgUrl; ?>');">
        <div class="block-title">
            <strong id="block-new-customer-heading" role="heading" aria-level="2"><?= $block->escapeHtml(__('Create an account')) ?></strong>
        </div>
        <div class="block-content" aria-labelledby="block-new-customer-heading">
            <p><?= $block->escapeHtml(__('By creating an account with our store, you will be able to move through the checkout process faster, store multiple shipping addresses, view and track your orders in your account and more')) ?></p>
            <div class="actions-toolbar">
                <div class="primary">
                    <a href="<?= $block->escapeUrl($block->getCreateAccountUrl()) ?>" class="action create primary"><span><?= $block->escapeHtml(__('Create an Account')) ?></span></a>
                </div>
            </div>
        </div>
    </div>
<?php endif; ?>
